### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by ZisBoom** [premnirmal/StockTicker#330] opened 2023-05-05 15:44 UTC
Widget is showing stale data for prices.
Launching app shows "Failed to fetch" and cached data for quotes a few days old.

News for stocks works.
At least one other Android play store review mentions same.

Android Pixel 3 XL
Stocks Widget version 3.9.819

**Comment by ZisBoom** [comment] 2023-05-05 15:50
Uninstall of the app and reinstall still has same issue, though the cached prices seem older. Not sure if app brings a starting cache with it.

**Comment by cirkuitnet** [comment] 2023-05-05 15:56
Duplicate of https://github.com/premnirmal/StockTicker/issues/328 

The issue is that Yahoo (sometimes) requires a session cookie to access their API. Simple solutions are out there. Here's a little bash script that I use that has implemented the session cookies to successfully resolve this issue:
https://github.com/pstadler/ticker.sh/blob/acquire-yahoo-finance-session/ticker.sh

Hopefully this helps, thanks!

**Comment by dmancine** [comment] 2023-05-05 17:35
I'm having the same issue. I don't understand the workarounds that have been posted. Do I have a Yahoo cookie in my app?

**Comment by cirkuitnet** [comment] 2023-05-05 17:37
I believe the change will need to be made to the source code of the app and a new release will need to be installed on our devices when the update ready.

**Comment by bjlockie** [comment] 2023-05-05 21:03
Same version of the app, same problem.

**Comment by premnirmal** [comment] 2023-05-06 06:45
Thank you, I will update to get the crumb and set cookies prior to requesting quotes

**Comment by premnirmal** [comment] 2023-05-08 07:39
I have created a pull request for retrieiving the cookies and the crumb, but it still needs a bit of work: https://github.com/premnirmal/StockTicker/pull/331 if anyone can help fix this please let us know, thank you

**Comment by sjaanus** [comment] 2023-05-08 10:03
Love to see this is getting attention!

**Comment by sterlingbeason** [comment] 2023-05-09 06:33
I've seen other projects downgrading the API version from v7 to v6 and it has resolved issues until more permanent solutions are developed. Maybe that can be done here to get a fix out quickly. Just swap out "v7" for "v6"  
https://github.com/premnirmal/StockTicker/blob/12765b974adf9669042664d82d1ec68f7d8028d0/app/src/main/res/values/strings.xml#L9

**Comment by jurgen178** [comment] 2023-05-09 17:34
I have it working:
finance.yahoo.com sends 3 cookies. With the CookieJar, you get them with GET finance.yahoo.com
Then for each retrofit request you add the cookieJar. It is not only required for the https://query1.finance.yahoo.com/v1/test/getcrumb, but also for any other query link.

I have been inspired by your app and have a created my own version of it. I hope my changes can contribute to a solution.

In the main activity, I'm getting the cookies, and when that succeeded, I move on to get the crumb. When I have the crumb, I update the UI:

        // Start getting the cookies and the crumb.
        stockRoomViewModel.getYahooCookie()

        // Get the crumb value with the acquired cookie.
        SharedRepository.yahooCookieReadyLiveData.observe(this, Observer {
            if (it) {
                stockRoomViewModel.getYahooCrumb()
            }
        })

        // Crumb is ready for use.
        SharedRepository.yahooCrumbLiveData.observe(this, Observer {
            stockRoomViewModel.runOnlineTaskNow()
        })

The crumb parameter is simply added to the interface:

```
interface YahooApiMarketData {
    @GET("quote?format=json")
    fun getStockDataAsync(
        @Query(
            value = "symbols"
        ) symbols: String,
        @Query(
            value = "crumb"
        ) crumb: String
    ): Deferred<Response<YahooResponse>>
}
```

The CookieJar:
```
class YahooCookieJar : CookieJar {

    private var cookieJar : List<Cookie> = listOf()

    override fun saveFromResponse(url: HttpUrl, cookies: List<Cookie>) {
        cookieJar = cookies
    }

    override fun loadForRequest(url: HttpUrl): List<Cookie> {
        return cookieJar
    }
}

private val yahooCookieJar: YahooCookieJar by lazy {
    YahooCookieJar()
}
```

And then add it to the retrofit requests:

    // building http request url
    private fun retrofit(): Retrofit = Retrofit.Builder()
        .client(
            OkHttpClient().newBuilder()
                .cookieJar(yahooCookieJar)
                
                
See the code in [StockApiFactory.kt](https://github.com/jurgen178/StockRoom/blob/5f59aa1e5951825721383f24a254f6dd7a98f3d2/app/src/main/java/com/thecloudsite/stockroom/StockApiFactory.kt#L95)

I have uploaded a working build to PlayStore
https://play.google.com/store/apps/details?id=com.thecloudsite.stockroom

The src for the app is in branch 'version 14' https://github.com/jurgen178/StockRoom/tree/version14

**Comment by ZisBoom** [comment] 2023-05-10 15:13
New version landed on my phone, and it's working.  Came with a nice bump on the main stock price I'm watching, so I look forward to future app updates as well. :)  Nice work, all.

**Comment by jpl-mac** [comment] 2023-05-10 16:45
I don't see a new version in F-droid, am i missing something?

**Comment by premnirmal** [comment] 2023-05-10 18:02
F-droid releases are controlled by f-droid, best ask them

**Comment by gajwani** [comment] 2023-05-10 18:07
@jpl-mac @premnirmal The user @ZisBoom didn't mention that they got it from F-Droid, they may have gotten it by manually downloading the APK or using a different F-Droid repository. I also don't see the new version on F-Droid default repo, and from what I know, they take quite a bit of time to publish new builds (F-Droid re-builds all apps itself to avoid the issue of binaries that are not the same as the published source code).

**Comment by jpl-mac** [comment] 2023-05-10 20:00
@gajwani Thanks for the reply.  I guess i didn't ask the right question.  I'll try again.  Where else can I find the app or apk other than f-droid?
Cheers

**Comment by cirkuitnet** [comment] 2023-05-13 15:53
I got the update through F-Droid today, everything is working as expected. Thanks for the efforts!

**Closed** 2023-05-14 20:31 UTC
Labels: bug, help wanted

**Comment by ZisBoom** [comment] 2023-05-15 06:44
Late return to the party, but just FYI I simply use the normal Google Play Store with auto update enabled for most apps.  Whatever y'all did seemed to flow to me faster than some.

**Comment by mrmotallebi** [comment] 2023-05-18 04:48
I'm curious, before this change the API would get called without any cookies and now it requires a cookie? It would be good if you can clarify its effect on tracking.
