### ISSUE TITLE
Make currency display optional

### ISSUE THREAD

**Issue by elerch** [premnirmal/StockTicker#192] opened 2021-02-04 20:49 UTC
The most recent F-Droid update included [currency on the widget](https://github.com/premnirmal/StockTicker/pull/168/commits/736faaf0f1fbce77989a50d6953c969bc4bba27a). I know over the years this project has struggled a bit with information density on the widget. I think this is a great change for a lot of people, but I suspect there are also a significant portion of users (like myself) that have a single currency portfolio, or would prefer to just remember the currency to have the widget real estate available to price/%/etc. It would be good to allow currency display to be optional - even with changing to small font size, the combination of currency and the tickers I'm tracking [high values](https://github.com/premnirmal/StockTicker/issues/179) still get chopped off in this latest update.

I like the idea of just [templating the widget](https://github.com/premnirmal/StockTicker/issues/187), but making currency optional might help in the short term.

**Comment by premnirmal** [comment] 2021-02-05 12:15
please check existing issues before opening new ones. This is a duplicate of https://github.com/premnirmal/StockTicker/issues/189, and it was fixed in 61893fc9935fb4265ade90d287495582951200e2, v3.9.733

**Closed by premnirmal** 2021-02-05 12:15 UTC
